### ISSUE TITLE
Relative paths not parsed correctly

### ISSUE THREAD

**Issue by PaulRBerg** [CoinageCrypto/solidifier#5]
Take this [contracts](https://github.com/MainframeHQ/mainframe-lending-protocol/tree/14178ab968d0037c6338e02bc1ff440c58fa7d3f/contracts) folder.

It compiles locally, with [buidler](https://github.com/nomiclabs/buidler), but in [solidifier.coina.ge](https://solidifier.coina.ge/), I'm getting this error:

```
An error was encountered while trying to parse your solidity code. Error details:

Error
Unable to find contract at path 'FintrollerInterface.sol'. Most likely you need to start from a different base directory when you drag your contracts in, or it is also possible that your contracts don't compile.
Error: Unable to find contract at path 'FintrollerInterface.sol'. Most likely you need to start from a different base directory when you drag your contracts in, or it is also possible that your contracts don't compile.
    at https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:16:31055
    at tryCatch (https://solidifier.coina.ge/app-f20ae4fd987160862351.js:2:30551)
    at Generator._invoke (https://solidifier.coina.ge/app-f20ae4fd987160862351.js:3:602)
    at Generator.prototype.<computed> [as next] (https://solidifier.coina.ge/app-f20ae4fd987160862351.js:2:30835)
    at step (https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:16:27930)
    at https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:16:28134
    at new Promise (<anonymous>)
    at https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:16:27849
    at https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:17:1008
    at https://solidifier.coina.ge/component---src-pages-index-js-a1de72575a9d8dd31d60.js:17:475

This usually means you have invalid syntax that solc would not be able to compile. Correct any syntax errors and try again.
```

**Comment by thekevinbrown** [comment]
Fair enough. We've actually moved to Buidler and/or Lamington ourselves, so my first suggestion would be to focus there. I'll queue up a task to deprecate this project and note that that's the case on the repo.
